# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 07:00
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=blog.models.ListField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
